//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamentos
    {
        public int Id { get; set; }
        public Nullable<int> CodigoDepartamento { get; set; }
        public string Nombre { get; set; }
    }
}
