//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int id { get; set; }
        public Nullable<int> CodigoEmpleado { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public Nullable<long> Telefono { get; set; }
        public string Departarmento { get; set; }
        public string Cargo { get; set; }
        public Nullable<System.DateTime> FechaI { get; set; }
        public Nullable<decimal> Salario { get; set; }
        public string Estatus { get; set; }
    }
}
