//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos
    {
        public int id { get; set; }
        public string Empleado { get; set; }
        public Nullable<System.DateTime> Desde { get; set; }
        public Nullable<System.DateTime> Hasta { get; set; }
        public string Comentarios { get; set; }
    }
}
